Запуск тестов в Docker
cusodede/yii2-s3-module pull request #14
Opened 2022-04-04 06:30 UTC by s1lver

Пулимся один раз

`make build`

Запускаем тесты для разных версии PHP

`make test`

2022-04-06 12:28 UTC, pozitronik requested changes, later dismissed
Сделайте, плз, ветку в этой репе.

2022-04-06 13:11 UTC, s1lver commented
> Сделайте, плз, ветку в этой репе.

`gh pr checkout 14` не подходит?

2022-04-06 13:15 UTC, pozitronik commented
> > Сделайте, плз, ветку в этой репе.
> 
> `gh pr checkout 14` не подходит?

Я ленивая жопа, не ставлю гитхабовский клиент отдельно.
Ладно, забей, в шторме позырю.

2022-04-11 10:01 UTC, pozitronik reviewed
`>make build`
всё отлично.
```
>make test
...всякая малафья
Creating minio-s3    ... done
Creating postgres-s3 ... done
Creating yii2-s3-module_php80_run ... done
standard_init_linux.go:228: exec user process caused: no such file or directory
ERROR: 1

** error 1 ** deleting test80
```

2022-04-11 10:27 UTC, pozitronik commented
> `>make build` всё отлично.
> 
> ```
> >make test
> ...всякая малафья
> Creating minio-s3    ... done
> Creating postgres-s3 ... done
> Creating yii2-s3-module_php80_run ... done
> standard_init_linux.go:228: exec user process caused: no such file or directory
> ERROR: 1
> 
> ** error 1 ** deleting test80
> ```

1. В обеих Dockerfile и в entrypoint.sh нужно было изменить переносы с виндовых на юниксовые
2. В Dockerfile заменить вызовы
`ENTRYPOINT ["tests/docker/php/entrypoint.sh"]`
на 
`ENTRYPOINT ["sh", "tests/docker/php/entrypoint.sh"]`

2022-04-11 10:29 UTC, pozitronik commented
Локально тесты падают:

```
In Db.php line 583:
                                                                           
  [Codeception\Exception\ModuleException]                                  
  Db: SQLSTATE[08006] [7] could not connect to server: Connection refused  
        Is the server running on host "localhost" (127.0.0.1) and accepting      
        TCP/IP connections on port 5432?                                         
  could not connect to server: Cannot assign requested address             
        Is the server running on host "localhost" (::1) and accepting            
        TCP/IP connections on port 5432? while creating PDO connection       
```

2022-04-25 10:36 UTC, s1lver commented
> Локально тесты падают:
> 
> ```
> In Db.php line 583:
>                                                                            
>   [Codeception\Exception\ModuleException]                                  
>   Db: SQLSTATE[08006] [7] could not connect to server: Connection refused  
>         Is the server running on host "localhost" (127.0.0.1) and accepting      
>         TCP/IP connections on port 5432?                                         
>   could not connect to server: Cannot assign requested address             
>         Is the server running on host "localhost" (::1) and accepting            
>         TCP/IP connections on port 5432? while creating PDO connection       
> ```

Вообще странно. Может у тебя какие-то старые конфиги остались?

2022-04-25 10:43 UTC, pozitronik commented
> > Локально тесты падают:
> > ```
> > In Db.php line 583:
> >                                                                            
> >   [Codeception\Exception\ModuleException]                                  
> >   Db: SQLSTATE[08006] [7] could not connect to server: Connection refused  
> >         Is the server running on host "localhost" (127.0.0.1) and accepting      
> >         TCP/IP connections on port 5432?                                         
> >   could not connect to server: Cannot assign requested address             
> >         Is the server running on host "localhost" (::1) and accepting            
> >         TCP/IP connections on port 5432? while creating PDO connection       
> > ```
> 
> Вообще странно. Может у тебя какие-то старые конфиги остались?

хз.

2022-04-25 11:04 UTC, s1lver commented
> > > Локально тесты падают:
> > > ```
> > > In Db.php line 583:
> > >                                                                            
> > >   [Codeception\Exception\ModuleException]                                  
> > >   Db: SQLSTATE[08006] [7] could not connect to server: Connection refused  
> > >         Is the server running on host "localhost" (127.0.0.1) and accepting      
> > >         TCP/IP connections on port 5432?                                         
> > >   could not connect to server: Cannot assign requested address             
> > >         Is the server running on host "localhost" (::1) and accepting            
> > >         TCP/IP connections on port 5432? while creating PDO connection       
> > > ```
> > 
> > 
> > Вообще странно. Может у тебя какие-то старые конфиги остались?
> 
> хз.

Очень похоже на это. Тут нигде не используется стандартное подключение. Надо смотреть глазами на твои файлы конечно. Нет идей...

2022-04-26 06:42 UTC, pozitronik commented
> 
> Очень похоже на это. Тут нигде не используется стандартное подключение. Надо смотреть глазами на твои файлы конечно. Нет идей...

Я покопаюсь, как будет время. Пока не горит.

2022-05-03 09:16 UTC, pozitronik commented
Разобрался. У тебя в инструкции нет инфы о том, что надо сделать `cp tests/.env.example tests/.env`

2022-05-03 09:21 UTC, merged

2022-05-03 17:31 UTC, s1lver commented
> Разобрался. У тебя в инструкции нет инфы о том, что надо сделать `cp tests/.env.example tests/.env`

Вот же это делается в команде `make build`
```
@cp -nfr ./tests/.env.example ./tests/.env
```

2022-05-03 20:39 UTC, pozitronik commented
> > Разобрался. У тебя в инструкции нет инфы о том, что надо сделать `cp tests/.env.example tests/.env`
> 
> Вот же это делается в команде `make build`
> 
> ```
> @cp -nfr ./tests/.env.example ./tests/.env
> ```
> 
> Не надо ничего было дополнительно копировать никуда.

Ну если бы это у меня срабатывало, то проблем не возникало.