Add Tags
cusodede/yii2-s3-module pull request #16
Opened 2022-04-05 20:12 UTC by mvaload

2022-04-06 12:28 UTC, pozitronik requested changes
<s>Сделайте, плз, ветку в этой репе.</s>

Ладно, забейте.

2022-04-06 13:18 UTC, pozitronik commented
S3 поддерживает нативные теги, логично их использовать.

2022-04-08 14:00 UTC, mvaload commented
Насколько я понял  из документации https://docs.min.io/minio/baremetal/reference/minio-mc/mc-tag-set.html метки привязываются к ведрам с помощью команд в клиенте mc.

2022-04-08 14:06 UTC, pozitronik commented
> Насколько я понял из документации https://docs.min.io/minio/baremetal/reference/minio-mc/mc-tag-set.html метки привязываются к ведрам с помощью команд в клиенте mc.

Зачем тебе клиент, у нас API.
Просто добавь поддержку тегов в putObject, [вот пример](https://stackoverflow.com/questions/46248999/php-amazon-s3-uploads-and-tags). Теги перечисляются в формате query string.

Ессно, чтение тегов тоже должно быть реализовано, и поиск объекта по тегу, иначе смысла в них мало.

2022-04-11 06:50 UTC, alxlapin commented
@pozitronik Привет! Я правильно понимаю, что в проектах сейчас не используется таблица для хранения тегов? 
Если в интерфейсе потребуется вывести закрепленные за файлами теги, то это придется в s3 стучаться каждый раз?

2022-04-11 09:36 UTC, pozitronik requested changes
Не годится.
Предложенная реализация допускает только один тег для файла.
Нужно дать возможность привязывать к загрузке произвольное количество тегов, как это сделано в [yii2-filestorage](https://github.com/pozitronik/yii2-filestorage).

2022-04-11 09:39 UTC, closed without merging