Add method for remove object from storage
cusodede/yii2-s3-module pull request #23
Opened 2022-04-11 07:15 UTC by mvaload

2022-04-11 09:51 UTC, pozitronik requested changes

2022-04-11 09:51 UTC, pozitronik commented on src/helpers/S3Helper.php
> +    }
Табы, не пробелы.

2022-04-11 09:51 UTC, pozitronik commented on src/models/S3.php
> +    }
Табы, не пробелы. В проекте другое форматирование.

2022-04-11 09:51 UTC, pozitronik commented on src/helpers/S3Helper.php
> +        $storage->deleted = false;
Почему `deleted = false`?

2022-04-11 09:51 UTC, pozitronik commented on src/helpers/S3Helper.php
> +        return $storage->id;
Недостаточно проверок.
Что произойдёт, если запись `$storage` не сохранится?
Респонс `deleteObject()` никак не проверяется. Вдруг, например, файл уже был удалён?

Хорошо бы было написать тесты, чтобы проверить поведение.

2022-04-11 10:04 UTC, mvaload commented on src/helpers/S3Helper.php
> +        $storage->deleted = false;
Упс,  конечно же true.

2022-04-11 20:33 UTC, mvaload commented on src/helpers/S3Helper.php
> +        return $storage->id;
Не понял, как можно респонс deleteObject проверить, смотреть в DeleteMarker?

2022-04-11 20:34 UTC, pozitronik commented on src/helpers/S3Helper.php
> +        return $storage->id;
> Не понял, как можно респонс deleteObject проверить, смотреть в DeleteMarker?

Не знаю, думал ты разберёшься =)

2022-04-12 07:08 UTC, mvaload commented on src/helpers/S3Helper.php
> +        return $storage->id;
В общем провел рад экспериментов с удалением файлов. При удалении файла если он отсутствует в облаке ничего не происходит(запрос отрабатывает без ошибок), в респонсе постоянный набор данных(в основном метаданные), что есть файл, что его нет.

2022-04-12 10:44 UTC, alxlapin commented on src/controllers/IndexController.php
> +		if (null === $cloudStorage = CloudStorage::findOne($id)) throw new NotFoundHttpException();
функционал дублирует логику S3Helper. В контроллере надо вызывать тогда S3Helper::deleteFile()

2022-04-12 10:44 UTC, alxlapin commented on src/helpers/S3Helper.php
> +			throw new ServerErrorHttpException('Could not record');
HttpException в сервисных классах как-то не к месту

2022-04-12 10:44 UTC, alxlapin commented on src/helpers/S3Helper.php
> +		(new S3())->deleteObject($storage->key);
без указания бакета удалиться может либо ничего, либо то, что не надо удалять

2022-04-12 10:44 UTC, alxlapin commented on tests/unit/S3ModuleTest.php
> +		$result2 = S3Helper::deleteFile(rand());
было бы неплохо проверить, что файл действительно удалился, то есть попытаться этот файл получить из хранилища

2022-04-12 15:18 UTC, mvaload commented
Тесты не проходят, разбираюсь пока.

2022-04-13 10:27 UTC, mvaload commented
готово

2022-04-13 11:31 UTC, alxlapin commented on src/helpers/S3Helper.php
> +		if (false === $storage->save()) return null;
Размазанно получилось - null в данном случае связан с двумя несвязанными кейсами. Я предлагал тебе никак не реагировать на результат операции save(), т.к. считаю это излишним.
Призовем @pozitronik

2022-04-13 12:15 UTC, mvaload commented on src/helpers/S3Helper.php
> +		if (false === $storage->save()) return null;
В принципе согласен, так как мало вероятно, что модель не сохранится при записи одного поля с булевым значением.

2022-04-13 18:22 UTC, pozitronik requested changes

2022-04-13 18:22 UTC, pozitronik commented on src/controllers/IndexController.php
> +		if (null === $result) throw new NotFoundHttpException();
```suggestion
		if (null === S3Helper::deleteFile($id)) throw new NotFoundHttpException();
```

2022-04-13 18:22 UTC, pozitronik commented on src/helpers/S3Helper.php
> +use yii\web\ServerErrorHttpException;
unused

2022-04-13 18:22 UTC, pozitronik commented on src/helpers/S3Helper.php
> +		if (null === $storage = CloudStorage::find()->where(['id' => $storageId, 'deleted' => false])->one()) return null;
```suggestion
		if (null === $storage = CloudStorage::find()->where(['id' => $storageId])->active()->one()) return null;
```

2022-04-13 18:22 UTC, pozitronik commented on src/helpers/S3Helper.php
> +		if (null === $storage = CloudStorage::find()->where(['id' => $storageId, 'deleted' => false])->one()) return null;
```suggestion
		if (null === $storage = CloudStorage::find()->where(['id' => $storageId])->active()->one()) return null;
```

2022-04-13 18:22 UTC, pozitronik commented on src/helpers/S3Helper.php
> +		if (false === $storage->save()) return null;
Ну, например.
```suggestion
		if (false === $storage->save()) throw new Exception("Смерть жопа");
```
Неудача записи в БД как бы является реально непредусмотренной и катастрофической ситуацией, никак не относящейся к логике функции.
Но поскольку у нас вообще-то следит за этим фреймворк, то достаточно
```suggestion
		$storage->save();
```

2022-04-13 18:22 UTC, pozitronik commented on tests/unit/S3ModuleTest.php
> +		$result2 = S3Helper::deleteFile(mt_rand());
А чего рандом? У тебя БД перед каждым тестом заново создаётся, id > 1 всегда пустые (хотя это может измениться в будущем при смене настроек тестов, но маловероятно).

2022-04-13 18:22 UTC, pozitronik commented on src/helpers/S3Helper.php
> +        return $storage->id;
> В общем провел рад экспериментов с удалением файлов. При удалении файла если он отсутствует в облаке ничего не происходит(запрос отрабатывает без ошибок), в респонсе постоянный набор данных(в основном метаданные), что есть файл, что его нет.

Да, похоже на то. Ну ок.

2022-04-14 06:36 UTC, mvaload commented
Поправил.

2022-04-14 11:22 UTC, pozitronik commented on tests/unit/S3ModuleTest.php
> +		$result2 = S3Helper::deleteFile(rand());
Добавил в тест

2022-04-14 11:23 UTC, pozitronik approved these changes

2022-04-14 11:30 UTC, alxlapin approved these changes

2022-04-14 11:32 UTC, merged