Issue 42
cusodede/yii2-s3-module pull request #43
Opened 2023-08-31 09:27 UTC by antonshevelev

2023-08-31 12:30 UTC, pozitronik commented
Чини тесты

2023-08-31 12:35 UTC, antonshevelev commented
Последний коммит пока только для проверки

2023-08-31 13:29 UTC, antonshevelev commented
Причина почему поломались тесты: либа [aws/](https://packagist.org/packages/aws/)aws-sdk-php начиная с версии 3.280.0 требует указания обязательного параметра region, которому раньше можно было присвоить значение пустой строки. (src/models/S3.php:71)

На что может повлиять этот параметр нужно изучать. Самым безопасным считаю пока ограничить максимальную версию библиотеки `"aws/aws-sdk-php": "~3.279.0"`, поскольку отношения к  текущей задаче это не имеет.

PS в списке регионов нет ничего относящегося к России https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
Как я понял это связанно с текущей политической ситуацией.

@pozitronik что думаешь?

2023-09-01 09:27 UTC, pozitronik commented
Судя по [той же](https://docs.aws.amazon.com/general/latest/gr/rande.html) доке, регионы — это способ указания предпочтительной региональной ноды при работе с «настоящим» амазоном. Для S3 это вообще пофигу.
Чтобы не лочить версию, можно просто засунуть в конфиг по дефолту любое легитимное значение (например `il-central-1`).
@antonshevelev попробуй так сделать.

2023-09-02 07:18 UTC, pozitronik requested changes
Чтобы не лочить версию, можно просто засунуть в конфиг по дефолту любое легитимное значение (например `il-central-1`).

2023-09-04 08:44 UTC, s1lver requested changes

2023-09-04 08:44 UTC, s1lver commented on tests/docker-compose.yml
> +    command: -c 'mkdir -p /data/testbucket && mkdir -p /data/first-bucket && mkdir -p /data/second-bucket && minio server --console-address ":9009" --address ":9008" /data'
В чем смысл переименовывать директории?

2023-09-04 08:45 UTC, s1lver commented
> Причина почему поломались тесты: либа [aws/](https://packagist.org/packages/aws/)aws-sdk-php начиная с версии 3.280.0 требует указания обязательного параметра region, которому раньше можно было присвоить значение пустой строки. (src/models/S3.php:71)
> 
> На что может повлиять этот параметр нужно изучать. Самым безопасным считаю пока ограничить максимальную версию библиотеки `"aws/aws-sdk-php": "~3.279.0"`, поскольку отношения к текущей задаче это не имеет.
> 
> PS в списке регионов нет ничего относящегося к России https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints Как я понял это связанно с текущей политической ситуацией.
> 
> @pozitronik что думаешь?

Это известная проблема. Тут даже есть Issue на это #40

2023-09-04 08:47 UTC, antonshevelev commented on tests/docker-compose.yml
> +    command: -c 'mkdir -p /data/testbucket && mkdir -p /data/first-bucket && mkdir -p /data/second-bucket && minio server --console-address ":9009" --address ":9008" /data'
Бакеты не создавались с таким неймингом, тесты падали

2023-09-19 11:38 UTC, pozitronik approved these changes

2023-09-20 08:10 UTC, antonshevelev commented
@pozitronik ждем аппрува от Жени @s1lver? Или вливаем?

2023-09-20 08:19 UTC, merged

2023-09-20 08:20 UTC, pozitronik commented
@antonshevelev новый тег к мастеру добавишь?

2023-09-20 08:32 UTC, antonshevelev commented
`git tag <tagname>` оно? Что устанавливаем в тег? @pozitronik

2023-09-20 08:36 UTC, pozitronik commented
> `git tag <tagname>` оно? Что устанавливаем в тег? @pozitronik

`1.0.17`
потом `git push --tags`

2023-09-20 08:59 UTC, antonshevelev commented
@pozitronik done

2023-09-20 09:00 UTC, pozitronik commented
> @pozitronik done

В релизах до сих пор предыдущая версия.

2023-09-20 09:02 UTC, antonshevelev commented
@pozitronik "Create release" релиз я не нажимал? Жду?)

2023-09-20 09:04 UTC, pozitronik commented
> @pozitronik "Create release" релиз я не нажимал? Жду?)

После того, как ты добавил и запушил новый тег для master, он автоматически добавляется в релизы, и обновляется актуальная версия в composer. Возможно, ты не на ту ветку тег добавил?

2023-09-20 09:07 UTC, antonshevelev commented
всё делал в мастере